spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/tests
      username: root
      password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tests
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true